name: Build Desktop

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build Desktop App on current platform
        working-directory: ./desktop
        run: |
          npm install
          npm run build
          npm run make:current


      - name: Upload Windows Artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: leafbox-windows
          path: |
            desktop/out/make/**/*.exe
            desktop/out/make/**/*.zip

      - name: Upload Linux Artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: leafbox-linux
          path: |
            desktop/out/make/**/*.rpm
            desktop/out/make/**/*.deb
            desktop/out/make/**/*.zip

      - name: Upload macOS Artifacts
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: leafbox-macos
          path: |
            desktop/out/make/**/*.dmg
        